from typing import Protocol, runtime_checkable
from uuid import UUID

from use_cases.shared.persistence import SourceItemRecord
from use_cases.shared.types import SourceItem


@runtime_checkable
class SourceItemRepository(Protocol):
    def add(self, record: SourceItemRecord) -> None: ...

    def get(self, source_item_id: UUID) -> SourceItemRecord | None: ...

    def require(self, source_item_id: UUID) -> SourceItem: ...

    def list_by_session(self, session_id: UUID) -> list[SourceItemRecord]: ...

    def list_domain_by_session(self, session_id: UUID) -> list[SourceItem]: ...

    def update(self, record: SourceItemRecord) -> None: ...

    def delete(self, source_item_id: UUID) -> None: ...
