from typing import Protocol
from uuid import UUID

from domain.models import ArchiveVolume, Session, SourceItem


class SessionRepository(Protocol):
    def add(self, session: Session) -> None: ...

    def get(self, session_id: UUID) -> Session | None: ...

    def update(self, session: Session) -> None: ...


class SourceItemRepository(Protocol):
    def add(self, source_item: SourceItem) -> None: ...

    def get(self, source_item_id: UUID) -> SourceItem | None: ...

    def list_by_session(self, session_id: UUID) -> list[SourceItem]: ...

    def update(self, source_item: SourceItem) -> None: ...


class ArchiveVolumeRepository(Protocol):
    def add(self, volume: ArchiveVolume) -> None: ...

    def list_by_source_item(self, source_item_id: UUID) -> list[ArchiveVolume]: ...

    def update(self, volume: ArchiveVolume) -> None: ...
