from typing import Protocol, runtime_checkable
from uuid import UUID

from use_cases.persistence import ArchiveVolumeRecord
from use_cases.types import ArchiveVolume


@runtime_checkable
class ArchiveVolumeRepository(Protocol):
    def add(self, record: ArchiveVolumeRecord) -> None: ...

    def get(self, volume_id: UUID) -> ArchiveVolumeRecord | None: ...

    def require(self, volume_id: UUID) -> ArchiveVolume: ...

    def list_by_source_item(self, source_item_id: UUID) -> list[ArchiveVolumeRecord]: ...

    def list_domain_by_source_item(self, source_item_id: UUID) -> list[ArchiveVolume]: ...

    def list_by_session(self, session_id: UUID) -> list[ArchiveVolumeRecord]: ...

    def require_for_session(self, session_id: UUID) -> list[ArchiveVolume]: ...

    def update(self, record: ArchiveVolumeRecord) -> None: ...
