from typing import Protocol
from uuid import UUID


class TaskQueuePort(Protocol):
    def enqueue_archive(self, source_item_id: UUID) -> None: ...

    def enqueue_upload(self, archive_volume_id: UUID) -> None: ...

    def enqueue_cleanup(self, archive_volume_id: UUID) -> None: ...

    def enqueue_restore(self, archive_volume_id: UUID) -> None: ...
